#!/bin/sh

if [ -z "$JAVA_HOME" ] ; then
  JAVACMD=`which java`
else
  JAVACMD="$JAVA_HOME/bin/java"
fi

if [ ! -x "$JAVACMD" ] ; then
  echo "The JAVA_HOME environment variable is not defined correctly" >&2
  echo "This environment variable is needed to run this program" >&2
  echo "NB: JAVA_HOME should point to a JDK not a JRE" >&2
  exit 1
fi


installDir="NOTSET";

if [ -d "${HOME}/bin" ]; then
  installDir="${HOME}/bin"
fi

if [ -d "${HOME}/.local/bin" ]; then
  installDir="${HOME}/.local/bin"
fi

if [ "${installDir}" = "NOTSET" ]; then
  echo "Unable to determine installed directory?  Failing badly ..."
  exit 0;
fi

##
## assumes ebean-init.jar is also in .local/bin
##
exec "$JAVACMD" -jar "${installDir}/ebean-init.jar" "$@"
