#!/usr/bin/env bash

installHost="https://ebean.io";
installVersion="$(curl --insecure --silent "${installHost}/cli-dist/version.txt?_=$(date +%s)")";
installJar="ebean-init-${installVersion}.jar";
installUrl="${installHost}/cli-dist/${installJar}";

installDir="NOTSET";

if [ -d "${HOME}/bin" ]; then
  installDir="${HOME}/bin"
fi

if [ -d "${HOME}/.local/bin" ]; then
  installDir="${HOME}/.local/bin"
fi

if [ "${installDir}" = "NOTSET" ]; then
  echo "Unable to find ~/.local/bin or ~/bin directory to install into?  Failing to install ..."
  exit 0;
fi


if [ ! -f "${installDir}/${installJar}" ]; then
  echo "downloading ${installUrl} ..."
  curl -# --location --insecure "${installUrl}" > $installDir/$installJar
  rm -f $installDir/ebean-init.jar
  ln -s $installDir/$installJar $installDir/ebean-init.jar
fi

if [ ! -f $installDir/ebeaninit ]; then
  echo "setup ebean-init ..."
  curl -# --location --insecure "${installHost}/cli-dist/ebeaninit" > $installDir/ebeaninit
  chmod +x $installDir/ebeaninit
fi


echo ""
echo "Installed ebeaninit into: $installDir"
echo "done."

